# Basic DataFrame Analysis

* `sum`
* `min`
* `max`
* `median`
* `mean`
* `count`
* `describe`

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
pd.options.display.min_rows=20

In [5]:
import pandas as pd
houses = pd.read_csv("/content/drive/MyDrive/DEPI/Data/kc_house_data.csv")
houses

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180.0,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170.0,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770.0,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050.0,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680.0,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890.0,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715.0,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060.0,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050.0,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890.0,0,2003,0,98038,47.3684,-122.031,2390,7570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21603,7852140040,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,...,8,2270.0,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,...,8,1490.0,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,...,9,2520.0,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,...,9,2600.0,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,...,8,1180.0,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530.0,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310.0,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020.0,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600.0,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020.0,0,2008,0,98144,47.5941,-122.299,1020,1357

In [8]:
houses.min()

id                       1000102
date             20140502T000000
price                    75000.0
bedrooms                       0
bathrooms                    0.0
sqft_living                  290
sqft_lot                     520
floors                       1.0
waterfront                     0
view                           0
condition                      1
grade                          1
sqft_above                 290.0
sqft_basement                  0
yr_built                    1900
yr_renovated                   0
zipcode                    98001
lat                      47.1559
long                    -122.519
sqft_living15                399
sqft_lot15                   651
dtype: object

In [9]:
houses.max()

id                    9900000190
date             20150527T000000
price                  7700000.0
bedrooms                      33
bathrooms                    8.0
sqft_living                13540
sqft_lot                 1651359
floors                       3.5
waterfront                     1
view                           4
condition                      5
grade                         13
sqft_above                9410.0
sqft_basement               4820
yr_built                    2015
yr_renovated                2015
zipcode                    98199
lat                      47.7776
long                    -121.315
sqft_living15               6210
sqft_lot15                871200
dtype: object

In [11]:
type(houses.max())

pandas.core.series.Series

In [12]:
houses.sum()

id                                                  98994056770455
date             20141013T00000020141209T00000020150225T0000002...
price                                                11672925008.0
bedrooms                                                     72854
bathrooms                                                 45706.25
sqft_living                                               44952873
sqft_lot                                                 326506890
floors                                                     32296.5
waterfront                                                     163
view                                                          5064
condition                                                    73688
grade                                                       165488
sqft_above                                              38649028.0
sqft_basement                                              6300385
yr_built                                                  42599334
yr_renovated                                               1824186
zipcode                                                 2119758513
lat                                                   1027915.4151
long                                                  -2641408.943
sqft_living15                                             42935359
sqft_lot15                                               275964632
dtype: object

In [13]:
houses.sum(numeric_only=True)

id               9.899406e+13
price            1.167293e+10
bedrooms         7.285400e+04
bathrooms        4.570625e+04
sqft_living      4.495287e+07
sqft_lot         3.265069e+08
floors           3.229650e+04
waterfront       1.630000e+02
view             5.064000e+03
condition        7.368800e+04
grade            1.654880e+05
sqft_above       3.864903e+07
sqft_basement    6.300385e+06
yr_built         4.259933e+07
yr_renovated     1.824186e+06
zipcode          2.119759e+09
lat              1.027915e+06
long            -2.641409e+06
sqft_living15    4.293536e+07
sqft_lot15       2.759646e+08
dtype: float64

In [15]:
titanic = pd.read_csv("/content/drive/MyDrive/DEPI/Data/titanic.csv")
titanic.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"

In [16]:
titanic.sum()

pclass                                                    3004
survived                                                   500
name         Allen, Miss. Elisabeth WaltonAllison, Master. ...
sex          femalemalefemalemalefemalemalefemalemalefemale...
age          290.91672302548633953714718242680?245032363747...
sibsp                                                      653
parch                                                      504
ticket       2416011378111378111378111378119952135021120501...
fare         211.3375151.55151.55151.55151.5526.5577.958305...
cabin        B5C22 C26C22 C26C22 C26C22 C26E12D7A36C101?C62...
embarked     SSSSSSSSSCCCCSSSCCCCSSCCSCCCSSSCSSSCSSSCCCSCCS...
boat         211???310?D??496B??68A55548?778D?788?469???6D8...
body         ???135?????22124??????????????148?????????????...
home.dest    St Louis, MOMontreal, PQ / Chesterville, ONMon...
dtype: object

In [17]:
titanic.sum(numeric_only=True)

pclass      3004
survived     500
sibsp        653
parch        504
dtype: int64

In [19]:
names = ['sumlev', 'region', 'division', 'state', 'name', 'census2010pop', 'estimatesbase2010', 'popestimate2010', 'popestimate2011', 'popestimate2012', 'popestimate2013', 'popestimate2014', 'popestimate2015', 'popestimate2016', 'popestimate2017', 'popestimate2018', 'popestimate2019', 'popestimate042020', 'popestimate2020']
state_pops = pd.read_csv("/content/drive/MyDrive/DEPI/Data/nst-est2020.csv", names=names, header=0)
state_pops

,sumlev,region,division,state,name,census2010pop,estimatesbase2010,popestimate2010,popestimate2011,popestimate2012,popestimate2013,popestimate2014,popestimate2015,popestimate2016,popestimate2017,popestimate2018,popestimate2019,popestimate042020,popestimate2020
0,10,0,0,0,United States,308745538,308758105,309327143,311583481,313877662,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329398742,329484123
1,20,1,0,0,Northeast Region,55317240,55318414,55380764,55608318,55782661,55912775,56021339,56052790,56063777,56083383,56084543,56002934,55924275,55849869
2,20,2,0,0,Midwest Region,66927001,66929737,66975328,67164092,67348275,67576524,67765576,67885682,68018175,68160342,68263019,68340091,68357895,68316744
3,20,3,0,0,South Region,114555744,114563042,114869421,116019483,117264196,118397213,119666248,121049223,122419547,123611036,124649156,125686544,126494232,126662754
4,20,4,0,0,West Region,71945553,71946912,72101630,72791588,73482530,74173435,74933166,75751299,76570256,77267367,77841481,78300384,78622340,78654756
5,40,3,6,1,Alabama,4779736,4780118,4785514,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4920706,4921532
6,40,4,9,2,Alaska,710231,710246,713982,722349,730810,737626,737075,738430,742575,740983,736624,733603,732074,731158
7,40,4,8,4,Arizona,6392017,6392292,6407342,6473416,6556344,6634690,6732873,6832810,6944767,7048088,7164228,7291843,7393900,7421401
8,40,3,7,5,Arkansas,2915918,2916029,2921998,2941038,2952876,2960459,2968759,2979732,2991815,3003855,3012161,3020985,3029672,3030522
9,40,4,9,6,California,37253956,37254522,37319550,37636311,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39418894,39368078
10,40,4,8,8,Colorado,5029196,5029319,5047539,5121900,5193660,5270774,5352637,5454328,5543844,5617421,5697155,5758486,5798266,5807719
11,40,1,1,9,Connecticut,3574097,3574151,3579173,3588632,3595211,3595792,3595697,3588561,3579830,3575324,3574561,3566022,3561494,3557006
12,40,3,5,10,Delaware,897934,897947,899647,907590,915518,924062,933131,942065,949989,957942,966985,976668,984899,986809
13,40,3,5,11,District of Columbia,601723,601767,605282,620290,635737,651559,663603,677014,687576,697079,704147,708253,712185,712816
14,40,3,5,12,Florida,18801310,18804589,18846143,19055607,19302016,19551678,19853880,20219111,20627237,20977089,21254926,21492056,21688239,21733312
15,40,3,5,13,Georgia,9687653,9688737,9712209,9803630,9903580,9975592,10071204,10183353,10308442,10417031,10519389,10628020,10695662,10710017
16,40,4,9,15,Hawaii,1360301,1360304,1364004,1379562,1395199,1408822,1415335,1422999,1428885,1425763,1423102,1415615,1410587,1407006
17,40,4,8,16,Idaho,1567582,1567658,1570819,1584272,1595910,1612053,1632248,1652495,1684036,1719745,1752074,1789060,1818238,1826913
18,40,2,3,17,Illinois,12830632,12831572,12840545,12867783,12883029,12895778,12885092,12859585,12821709,12779893,12724685,12667017,12615162,12587530
19,40,2,3,18,Indiana,6483802,6484050,6490555,6517250,6538989,6570575,6596019,6611442,6637898,6662068,6698481,6731010,6752183,6754953
20,40,2,4,19,Iowa,3046355,3046877,3050819,3066772,3076844,3093935,3110643,3122541,3133210,3143734,3149900,3159596,3164115,3163561
21,40,2,4,20,Kansas,2853118,2853120,2858266,2869677,2886024,2894306,2901861,2910717,2912977,2910892,2912748,2912635,2915024,2913805
22,40,3,6,21,Kentucky,4339367,4339330,4348464,4370817,4387865,4406906,4416992,4429126,4440306,4455590,4464273,4472345,4477899,4477251
23,40,3,7,22,Louisiana,4533372,4533500,4544635,4576244,4602067,4626040,4645938,4666998,4681346,4673673,4664450,4658285,4650984,4645318
24,40,1,1,23,Maine,1328361,1328354,1327651,1328473,1328094,1328543,1331217,1329098,1332348,1335743,1340123,1345770,1349647,1350141
25,40,3,5,24,Maryland,5773552,5773787,5788784,5840241,5888375,5925197,5960064,5988528,6007014,6028186,6042153,6054954,6059529,6055802
26,40,1,1,25,Massachusetts,6547629,6547788,6566440,6614218,6664269,6715158,6764864,6797484,6827280,6863560,6885720,6894883,6898116,6893574
27,40,2,3,26,Michigan,9883640,9884112,9877597,9883053,9898289,9914802,9932033,9934483,9954117,9976752,9987286,9984795,9976330,9966555
28,40,2,4,27,Minnesota,5303925,5303933,5310934,5346620,5377500,5414722,5452665,5484002,5525360,5569283,5608762,5640053,5655855,5657342
29,40,3,6,28,Mississippi,2967297,2968129,2970615,2979147,2984599,2989839,2991892,2990231,2990595,2990674,2982879,2978227,2971253,2966786
30,40,2,4,29,Missouri,5988927,5988941,5996089,6011182,6026027,6042989,6059130,6075411,6091384,6111382,6125986,6140475,6151737,6151548
31,40,4,8,30,Montana,989415,989400,990730,997518,1004168,1014158,1022657,1031495,1042137,1053862,1061818,1070123,1078405,1080577
32,40,2,4,31,Nebraska,1826341,1826311,1829591,1840914,1853691,1865813,1879955,1892059,1906483,1916998,1925512,1932571,1937258,1937552
33,40,4,8,32,Nevada,2700551,2700683,2702483,2713114,2744670,2776956,2818935,2868531,2919555,2972097,3030725,3090771,3128500,3138259
34,40,1,1,33,New Hampshire,1316470,1316457,1316807,1320444,1324677,1327272,1334257,1337480,1343694,1350395,1355064,1360783,1365533,1366275
35,40,1,2,34,New Jersey,8791894,8791959,8799451,8828552,8845671,8857821,8867277,8870312,8873584,8888147,8891730,8891258,8890883,8882371
36,40,4,8,35,New Mexico,2059179,2059199,2064614,2080707,2087715,2092833,2090236,2090071,2092555,2092844,2093754,2099634,2106117,2106319
37,40,1,2,36,New York,19378102,19378117,19399956,19499921,19574362,19626488,19653431,19657321,19636391,19593849,19544098,19463131,19382373,19336776
38,40,3,5,37,North Carolina,9535483,9535762,9574586,9658913,9751810,9846717,9937295,10037218,10161802,10275758,10391358,10501384,10581885,10600823
39,40,2,4,38,North Dakota,672591,672575,674752,685526,702227,723149,738736,755537,756114,756755,760062,763724,765224,765309
40,40,2,3,39,Ohio,11536504,11536763,11539449,11545735,11550971,11579692,11606573,11622315,11640060,11665706,11680892,11696507,11699855,11693217
41,40,3,7,40,Oklahoma,3751351,3751582,3760014,3788824,3819320,3853891,3879187,3910518,3928143,3933602,3943488,3960676,3977682,3980783
42,40,4,9,41,Oregon,3831074,3831083,3837614,3872672,3900102,3924110,3965447,4018542,4093271,4147294,4183538,4216116,4237408,4241507
43,40,1,2,42,Pennsylvania,12702379,12702891,12711406,12747052,12769123,12779538,12792392,12789838,12788468,12794679,12809107,12798883,12794404,12783254
44,40,1,1,44,Rhode Island,1052567,1052970,1053994,1053829,1054893,1055560,1056511,1056886,1057816,1056554,1059338,1058158,1058004,1057125
45,40,3,5,45,South Carolina,4625364,4625358,4635846,4672655,4719027,4766469,4826858,4896006,4963031,5027102,5091702,5157702,5205864,5218040
46,40,2,4,46,South Dakota,814180,814198,816193,823740,833859,842751,849670,854663,863693,873732,879386,887127,891688,892717
47,40,3,6,47,Tennessee,6346105,6346281,6355518,6400298,6455752,6496943,6544617,6595354,6651277,6714748,6778180,6830325,6875939,6886834
48,40,3,7,48,Texas,25145561,25146072,25241897,25645504,26084120,26479646,26963092,27468531,27914064,28291024,28624564,28986794,29286467,29360759
49,40,4,8,49,Utah,2763885,2763891,2775413,2814797,2854146,2898773,2938327,2983626,3044241,3103540,3155153,3203383,3239542,3249879
50,40,1,1,50,Vermont,625741,625727,625886,627197,626361,626603,625693,625810,624366,625132,624802,624046,623821,623347
51,40,3,5,51,Virginia,8001024,8001046,8024004,8102437,8187456,8255861,8315430,8367303,8417651,8471011,8510920,8556642,8587217,8590563
52,40,4,9,53,Washington,6724540,6724540,6743009,6827479,6898599,6966252,7057531,7167287,7299961,7427951,7526793,7614024,7678379,7693612
53,40,3,5,54,West Virginia,1852994,1853008,1854265,1856606,1857446,1854768,1850569,1843332,1832435,1818683,1805953,1795263,1788150,1784787
54,40,2,3,55,Wisconsin,5686986,5687285,5690538,5705840,5720825,5738012,5753199,5762927,5775170,5793147,5809319,5824581,5833464,5832655
55,40,4,8,56,Wyoming,563626,563775,564531,567491,576656,582620,583159,586389,585243,579994,579054,580116,582030,582328
56,40,X,X,72,Puerto Rico,3725789,3726157,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325284,3193344,3193553,3167851,3159343

In [ ]:
state_pops.tail(52).head(51).sum(numeric_only=True)

sumlev                    2040
state                     1477
census2010pop        308745538
estimatesbase2010    308758105
popestimate2010      309327143
popestimate2011      311583481
popestimate2012      313877662
popestimate2013      316059947
popestimate2014      318386329
popestimate2015      320738994
popestimate2016      323071755
popestimate2017      325122128
popestimate2018      326838199
popestimate2019      328329953
popestimate042020    329398742
popestimate2020      329484123
dtype: int64

In [25]:
netflix = pd.read_csv("/content/drive/MyDrive/DEPI/Data/netflix_titles.csv", sep="|", index_col=0)

In [21]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [26]:
netflix.count()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
listed_in       8807
description     8807
dtype: int64

In [28]:
houses.mean(numeric_only=True)

id               4.580302e+09
price            5.400881e+05
bedrooms         3.370842e+00
bathrooms        2.114757e+00
sqft_living      2.079900e+03
sqft_lot         1.510697e+04
floors           1.494309e+00
waterfront       7.541757e-03
view             2.343034e-01
condition        3.409430e+00
grade            7.656873e+00
sqft_above       1.788396e+03
sqft_basement    2.915090e+02
yr_built         1.971005e+03
yr_renovated     8.440226e+01
zipcode          9.807794e+04
lat              4.756005e+01
long            -1.222139e+02
sqft_living15    1.986552e+03
sqft_lot15       1.276846e+04
dtype: float64

In [30]:
titanic.mean(numeric_only=True)

pclass      2.294882
survived    0.381971
sibsp       0.498854
parch       0.385027
dtype: float64

In [32]:
houses.median(numeric_only=True)

id               3.904930e+09
price            4.500000e+05
bedrooms         3.000000e+00
bathrooms        2.250000e+00
sqft_living      1.910000e+03
sqft_lot         7.618000e+03
floors           1.500000e+00
waterfront       0.000000e+00
view             0.000000e+00
condition        3.000000e+00
grade            7.000000e+00
sqft_above       1.560000e+03
sqft_basement    0.000000e+00
yr_built         1.975000e+03
yr_renovated     0.000000e+00
zipcode          9.806500e+04
lat              4.757180e+01
long            -1.222300e+02
sqft_living15    1.840000e+03
sqft_lot15       7.620000e+03
dtype: float64

In [33]:
titanic.median(numeric_only=True)

pclass      3.0
survived    0.0
sibsp       0.0
parch       0.0
dtype: float64

In [34]:
titanic.mode(numeric_only=True)

   pclass  survived  sibsp  parch
0       3         0      0      0

In [35]:
titanic.describe()

            pclass     survived        sibsp        parch
count  1309.000000  1309.000000  1309.000000  1309.000000
mean      2.294882     0.381971     0.498854     0.385027
std       0.837836     0.486055     1.041658     0.865560
min       1.000000     0.000000     0.000000     0.000000
25%       2.000000     0.000000     0.000000     0.000000
50%       3.000000     0.000000     0.000000     0.000000
75%       3.000000     1.000000     1.000000     0.000000
max       3.000000     1.000000     8.000000     9.000000

In [36]:
houses.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21611.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.396095,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.128162,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [37]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1309 non-null   object
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: int64(4), object(10)
memory usage: 143.3+ KB

In [39]:
titanic.describe(include=["object"])

,name,sex,age,ticket,fare,cabin,embarked,boat,body,home.dest
count,1309,1309,1309,1309,1309,1309,1309,1309,1309,1309
unique,1307,2,99,929,282,187,4,28,122,370
top,"Connolly, Miss. Kate",male,?,CA. 2343,8.05,?,S,?,?,?
freq,2,843,263,11,60,1014,914,823,1188,564

In [38]:
titanic.describe(include=["number"])

            pclass     survived        sibsp        parch
count  1309.000000  1309.000000  1309.000000  1309.000000
mean      2.294882     0.381971     0.498854     0.385027
std       0.837836     0.486055     1.041658     0.865560
min       1.000000     0.000000     0.000000     0.000000
25%       2.000000     0.000000     0.000000     0.000000
50%       3.000000     0.000000     0.000000     0.000000
75%       3.000000     1.000000     1.000000     0.000000
max       3.000000     1.000000     8.000000     9.000000

In [40]:
titanic.describe(include=["O"])

,name,sex,age,ticket,fare,cabin,embarked,boat,body,home.dest
count,1309,1309,1309,1309,1309,1309,1309,1309,1309,1309
unique,1307,2,99,929,282,187,4,28,122,370
top,"Connolly, Miss. Kate",male,?,CA. 2343,8.05,?,S,?,?,?
freq,2,843,263,11,60,1014,914,823,1188,564

In [42]:
netflix.describe(include="O")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,3207,1793,362,4

In [45]:
netflix.describe(include="number")

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000